Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Internal Server Error: /admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/admin.py", line 77, in import_csv
    return render(request, "admin/csv_form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock'. Did you forget to register or load this tag?
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/admin.py", line 77, in import_csv
    return render(request, "admin/csv_form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-details' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/accounts/users/(?P<pk>[0-9]+)/user\\-details/\\Z']
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-details' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/accounts/users/(?P<pk>[0-9]+)/user\\-details/\\Z']
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-details' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/accounts/users/(?P<pk>[0-9]+)/user\\-details/\\Z']
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-details' with keyword arguments '{'user_id': ''}' not found. 1 pattern(s) tried: ['ru/accounts/users/(?P<pk>[0-9]+)/user\\-details/\\Z']
Watching for file changes with StatReloader
Not Found: /sitemap.xml/
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-details' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/accounts/users/(?P<pk>[0-9]+)/user\\-details/\\Z']
Аутентификация пользователя admin1 прошла успешно
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 403, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_name.id"])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'user_name.id'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /sitemap.xml/
Not Found: /sitemap.xml/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sitemap.xml/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 187, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 92, in _get
    return attr(item)
           ^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 132, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/blogapp/models.py", line 65, in get_absolute_url
    return reverse('blogapp:article', kwargs={"pk": self.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' not found. 'article' is not a valid view function or pattern name.
Internal Server Error: /sitemap.xml/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 187, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 92, in _get
    return attr(item)
           ^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/sitemaps/__init__.py", line 132, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/blogapp/models.py", line 65, in get_absolute_url
    return reverse('blogapp:article', kwargs={"pk": self.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' not found. 'article' is not a valid view function or pattern name.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/blogapp/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/admin.py", line 77, in import_csv
    return render(request, "admin/csv_form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/admin.py", line 77, in import_csv
    return render(request, "admin/csv_form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock'. Did you forget to register or load this tag?
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 404, in get_queryset
    .filter(user=self.owner.usename) \
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'usename'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'admin1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 404, in get_queryset
    .filter(user=self.owner.username) \
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1275, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2057, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'admin1'.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 410, in get_context_data
    context["owner"] = self.owner
                       ^^^^^^^^^^
AttributeError: 'UserOrdersListView' object has no attribute 'owner'
Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 410, in get_context_data
    context["owner"] = self.owner
                       ^^^^^^^^^^
AttributeError: 'UserOrdersListView' object has no attribute 'owner'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/4/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 401, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 401, in get_queryset
    self.owner = User.objects.get_object_or_404(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserManager' object has no attribute 'get_object_or_404'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/23/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 401, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 119, in test_func
    raise NotImplementedError(
NotImplementedError: UserOrdersListView is missing the implementation of the test_func() method.
Internal Server Error: /ru/shop/users/2/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 119, in test_func
    raise NotImplementedError(
NotImplementedError: UserOrdersListView is missing the implementation of the test_func() method.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 402, in test_func
    return self.request.user == self.get_object().created_by
                                ^^^^^^^^^^^^^^^
AttributeError: 'UserOrdersListView' object has no attribute 'get_object'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 119, in test_func
    raise NotImplementedError(
NotImplementedError: UserOrdersListView is missing the implementation of the test_func() method.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/4/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 405, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 428, in __init__
    super().__init__(kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 443, in get
    OrderSerializer(self.queryset, many=True).data
                    ^^^^^^^^^^^^^
AttributeError: 'UserOrdersDataExportView' object has no attribute 'queryset'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 439, in get
    OrderSerializer(self.queryset, many=True).data
                    ^^^^^^^^^^^^^
AttributeError: 'UserOrdersDataExportView' object has no attribute 'queryset'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 440, in get
    OrderSerializer(self.user_orders, many=True).data
                    ^^^^^^^^^^^^^^^^
AttributeError: 'UserOrdersDataExportView' object has no attribute 'user_orders'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 440, in get
    OrderSerializer(self.owner, many=True).data
                    ^^^^^^^^^^
AttributeError: 'UserOrdersDataExportView' object has no attribute 'owner'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 429, in test_func
    return self.request.user == self.get_object().created_by \
                                ^^^^^^^^^^^^^^^
AttributeError: 'UserOrdersDataExportView' object has no attribute 'get_object'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 440, in get
    OrderSerializer(self.get_queryset, many=True).data
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'method' object is not iterable
Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 440, in get
    OrderSerializer(self.get_queryset(), many=True).data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'method' object is not iterable
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/1orders/
Not Found: /ru/shop/users/orders/export/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/4/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 445, in get
    OrderSerializer(self.get_queryset(), many=True).data
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 437, in get_queryset
    self.owner = User.objects.get(pk=self.kwargs["user_id"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 454, in get
    OrderSerializer(self.get_queryset(), many=True).data
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 256, in get_select
    select_mask = self.query.get_select_mask()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 773, in get_select_mask
    return self._get_only_select_mask(opts, mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 742, in _get_only_select_mask
    field = opts.get_field(field_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Order has no field named 'name'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/2/orders/export/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 453, in get
    OrderSerializer(self.get_queryset(), many=True).data
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1209, in get_related_selections
    if not select_related_descend(f, restricted, requested, select_mask):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query_utils.py", line 347, in select_related_descend
    raise FieldError(
django.core.exceptions.FieldError: Field Order.user cannot be both deferred and traversed using select_related at the same time.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/admin.py", line 77, in import_csv
    return render(request, "admin/csv_form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock'. Did you forget to register or load this tag?
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/4/orders/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py", line 421, in get_queryset
    for order in self.user_orders:
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1209, in get_related_selections
    if not select_related_descend(f, restricted, requested, select_mask):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query_utils.py", line 347, in select_related_descend
    raise FieldError(
django.core.exceptions.FieldError: Field Order.user cannot be both deferred and traversed using select_related at the same time.
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/4/orders/export/
Not Found: /ru/shop/uproducts
Запрошена страница со списком товаров
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Запрошена страница со списком товаров
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 320, in render
    if match:
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 256, in get_select
    select_mask = self.query.get_select_mask()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 773, in get_select_mask
    return self._get_only_select_mask(opts, mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 742, in _get_only_select_mask
    field = opts.get_field(field_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Order has no field named 'name'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ru/shop/orders/
Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'user.name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 320, in render
    if match:
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 256, in get_select
    select_mask = self.query.get_select_mask()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 773, in get_select_mask
    return self._get_only_select_mask(opts, mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 742, in _get_only_select_mask
    field = opts.get_field(field_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antongaranin/PycharmProjects/pythonProject/django/venv/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Order has no field named 'user.name'
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/1/orders/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/1/orders/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /ru/shop/users/1/orders/
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/antongaranin/PycharmProjects/pythonProject/django/M_17_DataExport/mysite/shopapp/views.py changed, reloading.
Watching for file changes with StatReloader
